# Generated by Django 4.1.2 on 2022-10-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBase',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('polymorphic_ctype',
                 models.ForeignKey(editable=False,
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='polymorphic_%(app_label)s.%(class)s_set+',
                                   to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FeedburnerWebsite',
            fields=[
                ('sourcebase_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='parsers.sourcebase')),
                ('url', models.CharField(max_length=256)),
                ('href_field', models.CharField(max_length=32)),
                ('date_field', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('parsers.sourcebase',),
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('sourcebase_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='parsers.sourcebase')),
                ('user_id', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('parsers.sourcebase',),
        ),
    ]
