version: "3.3"

services:

  frontend:
    restart: always
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    volumes:
      - backendstaticdata:/usr/share/nginx/html/backendstaticdata
    environment:
      - REACT_APP_URL=localhost
    ports:
      - 80:80
      - 443:443

  backend:
    restart: always
    build: backend
    env_file:
      - .env
    entrypoint: /scripts/backend-entrypoint.sh prod
    volumes:
      - backendstaticdata:/static

  celery:
    restart: always
    build: backend
    env_file:
      - .env
    entrypoint: /scripts/celery-entrypoint.sh
    depends_on:
      - backend
      - rabbit

  rabbit:
    restart: always
    image: rabbitmq:3.8.9-management-alpine
    env_file:
      - .env

  flower:
    restart: always
    image: mher/flower:0.9.5
    env_file:
      - .env
    depends_on:
      - rabbit

  postgres:
    restart: always
    image: postgres:13.1-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
  backendstaticdata:
