version: "3.3"

services:

  frontend:
    restart: always
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    volumes:
      - backendstaticdata:/usr/share/nginx/html/backendstaticdata
    environment:
      - REACT_APP_URL=localhost

  backend:
    restart: always
    build: backend
    env_file:
      - .env
    entrypoint: /scripts/backend-entrypoint.sh prod
    volumes:
      - backendstaticdata:/static

  celery:
    build: backend
    env_file:
      - .env
    entrypoint: /scripts/celery-entrypoint.sh
    depends_on:
      - backend
      - rabbit

  rabbit:
    image: rabbitmq:3.8.9-management-alpine
    env_file:
      - .env

  flower:
    image: mher/flower:0.9.5
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - rabbit

volumes:
  pgdata:
  backendstaticdata:
