version: "3.3"

services:
  backend:
    build: .
    volumes:
      - ./src:/app
      - ./scripts:/scripts
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
