# Generated by Django 4.0.6 on 2022-07-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('summary', models.TextField()),
                ('source', models.CharField(max_length=256)),
                ('href', models.CharField(max_length=256, null=True)),
                ('date', models.DateTimeField()),
                ('tags', models.ManyToManyField(related_name='news', to='api.tag')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-date'],
            },
        ),
    ]
