# Generated by Django 4.0.6 on 2022-08-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_twitteraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='user_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
