# Generated by Django 4.0.6 on 2022-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_twitteraccount_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('keywords', models.ManyToManyField(to='api.keyword')),
            ],
        ),
    ]
