# Generated by Django 4.0.6 on 2022-09-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_keyword_savedset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedset',
            old_name='title',
            new_name='name',
        ),
    ]
