# Generated by Django 4.0.6 on 2022-09-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='savedsets',
            field=models.ManyToManyField(blank=True, to='api.savedset'),
        ),
    ]
