# Generated by Django 4.1.2 on 2022-10-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '__first__'),
        ('api', '0007_alter_userprofile_savedsets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterAccount',
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='parsers.sourcebase'),
        ),
    ]
