# Generated by Django 4.1.2 on 2022-10-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_read_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedSet',
            new_name='Preset',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='savedsets',
            new_name='presets',
        ),
    ]
