# Generated by Django 4.1.2 on 2022-12-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_custompreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='content_type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
